### ISSUE TITLE
quickstep may cause NPE

### ISSUE THREAD

**Issue by tzaeschke** [tzaeschke/ode4j#18]
Quickstep may sometimes cause an NPE:

```
java.lang.NullPointerException
    at org.ode4j.ode.internal.DxQuickStep.dxQuickStepIsland_Stage1(DxQuickStep.java:1323)
    at org.ode4j.ode.internal.DxQuickStep.dxQuickStepIsland(DxQuickStep.java:1006)
    at org.ode4j.ode.internal.DxQuickStep.run(DxQuickStep.java:2037)
    at org.ode4j.ode.internal.processmem.DxIslandsProcessingCallContext.ThreadedProcessIslandStepper(DxIslandsProcessingCallContext.java:235)
    at org.ode4j.ode.internal.processmem.DxIslandsProcessingCallContext.access$3(DxIslandsProcessingCallContext.java:233)
    at org.ode4j.ode.internal.processmem.DxIslandsProcessingCallContext$4.run(DxIslandsProcessingCallContext.java:228)
    at org.ode4j.ode.threading.ThreadingTemplates$dxThreadedJobInfo.InvokeCallFunction(ThreadingImplTemplates.java:388)
    at org.ode4j.ode.threading.ThreadingTemplates$dxtemplateJobListSelfHandlertemplate.PerformJobProcessingSession(ThreadingImplTemplates.java:1105)
    at org.ode4j.ode.threading.ThreadingTemplates$dxtemplateJobListSelfHandlertemplate.PerformJobProcessingUntilExhaustion(ThreadingImplTemplates.java:1084)
    at org.ode4j.ode.threading.ThreadingTemplates$dxtemplateJobListSelfHandlertemplate.PrepareForWaitingAJobCompletion(ThreadingImplTemplates.java:1056)
    at org.ode4j.ode.threading.ThreadingTemplates$dxtemplateThreadingImplementation.WaitJobCompletion(ThreadingImplTemplates.java:1403)
    at org.ode4j.ode.threading.ThreadingImpl_H$dxSelfThreadedThreading.WaitJobCompletion(ThreadingImpl_H.java:1)
    at org.ode4j.ode.threading.DxThreadingImplementation$10.run(DxThreadingImplementation.java:342)
    at org.ode4j.ode.threading.DxThreadingBase.WaitThreadedCallExclusively(DxThreadingBase.java:179)
    at org.ode4j.ode.internal.DxWorld.dxProcessIslands(DxWorld.java:844)
    at org.ode4j.ode.internal.DxWorld.dWorldQuickStep(DxWorld.java:472)
    at org.ode4j.ode.internal.DxWorld.quickStep(DxWorld.java:1131)
    at org.ode4j.tests.TestIssue_0018.simLoop(TestIssue_0018.java:72)
    at org.ode4j.tests.TestIssue_0018.step(TestIssue_0018.java:192)
    at org.ode4j.tests.TestIssue_0018.test(TestIssue_0018.java:227)
```

**Comment by tzaeschke** [comment]
Closed as not reproducible,
